#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_dynamodb="0.0.1"
  jq -n --arg dynamodb "$ver_dynamodb" '{dynamodb: $dynamodb}'
}

version "$@"
